<div id="notification" class="index">
  <?php $jsAassetsUrl = PHPCI_URL . 'assets/js/'; ?>
  <script src="<?php print $jsAassetsUrl; ?>notify.js"></script>
  <script src="<?php print $jsAassetsUrl; ?>notifications/helper.js"></script>
  <script src="<?php print $jsAassetsUrl; ?>notifications/message.js"></script>
  <script src="<?php print $jsAassetsUrl; ?>notifications/notification.js"></script>
</div>